### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/models.rs:1194:46

### ISSUE THREAD

**Issue by jl94x4** [lostb1t/replex#82]
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/models.rs:1194:46
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/models.rs:1194:46

Getting this when trying to navigate recommended tab in my TV library and get this error;

![image](https://github.com/lostb1t/replex/assets/18123855/88dd02b8-2d3a-454e-8513-47cce5437f8f)

Using latest release

**Comment by jl94x4** [comment]
Getting this again on latest version @lostb1t 

[_thirsty_jennings_logs.txt](https://github.com/lostb1t/replex/files/12576981/_thirsty_jennings_logs.txt)

**Comment by jl94x4** [comment]
Seems to happen when I'm viewing a collection, and it loads more then it goes to something went wrong @lostb1t

**Comment by jl94x4** [comment]
![image](https://github.com/lostb1t/replex/assets/18123855/e9800305-aa7d-43df-add4-70031ee70c02)

All Libraries are affected by this
